name: CI pipeline

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubnatu-latest
    steps:
      -uses: actions/checkout@v5
      -name: Display message
       run: echo "buliding application"
      -name: run tests
       run:echo "testing succesfull"
      -name: Deploy
       run: echo "deployment successful"
    